### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by majedali117** [majedali117/BD2017#2]
Lab 2

**Comment by HorizonNet** [comment]
Below is a short review.

**Tasks**

- [ ] System Configuration Checks
- [ ] MySQL installation
- [ ] CM/CDH installation
- [x] Using the CM API
- [ ] Upgrade Cloudera Manager
- [x] Using a local parcel repository

Open points:

* System Configuration Checks
  * The command for the mount attributes of all volumes is wrong. Hint: You have to check a specific file on disk for that.
  * The command for listing the network configuration is wrong. Hint: You have to check a specific file on disk for that.
* MySQL installation
  * In `2-mysql-repo.md` your YUM repository should be listed, not the installation of MySQL server and the connector.
  * The databases for the different services are missing.
* CM/CDH installation
  * The screenshot in `4-cm-installed.png` is missing.
* Upgrade Cloudera Manager
  * This task is completely missing.

General feedback:

* Don't do commits via GitHub. Always ensure that you have the most recent version of your repository locally in case GitHub is down.
* Use proper Markdown formatting. Parts of your files are hard to read.
* Read the instructions carefully. You should use the file names we are looking for. Also, check which information really need to go into these files.

**Comment by HorizonNet** [comment]
I updated the review.
